name: Run lint

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Run eslint
        run: npm run lint:eslint

      - name: Run markdownlint
        run: npm run lint:markdown

      - name: Run Prettier
        run: npm run lint:prettier

      - name: Run actionlint
        run: npm run lint:action
